import { ethers } from "ethers";
import fs from "fs";
import path from "path";

// Load deployment info (address and ABI).  In a real project this file
// would be generated by Hardhat during deployment.  Here we provide a
// placeholder for illustration purposes.  At runtime you should ensure
// `deployment.json` exists with fields `address` and `abi`.
const deploymentPath = path.resolve("./deployment.json");
let contractAddress = null;
let contractAbi = null;
if (fs.existsSync(deploymentPath)) {
  const deployment = JSON.parse(fs.readFileSync(deploymentPath, "utf8"));
  contractAddress = deployment.address;
  contractAbi = deployment.abi;
}

// Create a provider and signer from environment variables.  When connecting
// to a local Hardhat node no private key is required to read data.  For
// write operations (grant/revoke consent) the patient must sign using their
// wallet (e.g. via MetaMask on the frontend).  Therefore, the backend
// mostly calls view functions and listens for events.
const provider = new ethers.JsonRpcProvider(process.env.RPC_URL || "http://127.0.0.1:8545");

/**
 * Get a contract instance for read-only calls.  If the ABI or address
 * have not been loaded the function will throw.
 */
function getContract() {
  if (!contractAddress || !contractAbi) {
    throw new Error("Consent contract ABI/address not configured");
  }
  return new ethers.Contract(contractAddress, contractAbi, provider);
}

export async function getConsent(patient, providerAddress) {
  const contract = getContract();
  return await contract.getConsent(patient, providerAddress);
}

export async function getConsentHistory(patient, providerAddress) {
  const contract = getContract();
  return await contract.getConsentHistory(patient, providerAddress);
}

// Additional functions for write operations could be defined here, but in a
// decentralized application it is better for the frontend (patient’s
// wallet) to send transactions directly.  The backend can still assist
// providers in requesting access by sending unsigned transactions or by
// broadcasting raw data.
